#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# bibtexvcs documentation build configuration file, created by
# sphinx-quickstart on Tue Mar  4 11:16:20 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../../'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.ifconfig',
    'alabaster',
]

source_suffix = '.rst'
source_encoding = 'utf-8-sig'
master_doc = 'index'

project = 'bibtexvcs'
copyright = '2014-2015, Michael Helmling'


import bibtexvcs
version = bibtexvcs.__version__
release = version

pygments_style = 'sphinx'

autodoc_member_order = 'bysource'
autodoc_default_flags = ['members']

rst_epilog = """
.. _JabRef: http://jabref.sourceforge.net

"""
html_theme = 'alabaster'
html_theme_options = {
    'description': "A collection of scripts to manage a BibTeX based literature database in a subversion repository",
    'github_user': 'supermihi',
    'github_repo': 'lpdec',
}
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'searchbox.html',
        'donate.html',
    ]
}

html_static_path = ['_static']
htmlhelp_basename = 'bibtexvcsdoc'

intersphinx_mapping = {
    'python': ('http://docs.python.org/3.5', None),
}
